[package]
name = "pm-linear"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
pm-core = { path = "../pm-core" }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
mockito = { workspace = true }
tokio = { workspace = true }
